\long\def\/*#1*/{} % Définition de \/*...*/ comme un bloc de commentaire.
\/*
	* Projet : ~~PROJET~~
	* Version : 1.0
	* description : ~~DESCR~~
	* Auteurs : ~~AUTEURS~~
	* Date de création : ~~DATE~~
	*/

%	%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%	%    INFORMATION(S) GÉNÉRALE(S)   %
%	%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
\NeedsTeXFormat{LaTeX2e}[199/01/01]
\ProvidesPackage{~~PROJET~~}[~~date~~ Extension personnelle, V1.0]
\LoadClass[a4paper, 12pt]{~~CLASSE~~} % Classe de mére



%	%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%	%       GESTION DES OPTIONS       %
%	%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%   TEST(S) SUR LES OPTIONS  %
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% UTILISATION(S) DES OPTIONS %
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
\DeclareOption*{} % Option inconnue

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%     FIN GESTION OPTIONS    %
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
\ProcessOptions % Fin de la prise d'option



%	%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%	%    IMPORTATIONS D'EXTENSIONS    %
%	%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%



%	%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%	%      CRÉATIONS DE COMPTEURS     %
%	%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%



%	%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%	%     DÉFINITION DES COMMANDES    %
%	%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%



%	%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%	% DÉCLARATIONS DES ENVIRONNEMENTS %
%	%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%



%	%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%	%   FIN DE LA CLASSE DE DOCUMENT  %
%	%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
           \endinput         %
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%



% #####-#####-#####-#####-##### FIN PROGRAMMATION #####-#####-#####-#####-##### %


